from pathlib import Path
import mansion_layout as m
root=Path(__file__).resolve().parents[1]
assert len(m.ROOM_NODES)==len(m.ROOMS)
assert all(m.room_at(p)>=0 for p in m.NODES)
reachable={0}
while True:
    expanded=reachable|{b for a,b in m.LINKS if a in reachable}|{a for a,b in m.LINKS if b in reachable}
    if expanded==reachable:break
    reachable=expanded
assert len(reachable)==len(m.NODES),'Disconnected mansion navigation node'
assert all(m.room_at(p)>=0 for pair in m.STARTS for p in pair)
lines=['// Generated by Tools/generate_mansion_layout.py; edit mansion_layout.py.','#pragma once','#include "CoreMinimal.h"','namespace SpychoHouse','{',f'    constexpr int32 RoomCount={len(m.ROOMS)};', '    constexpr float RoundSeconds=120.f;',
 '    struct FRoom { const TCHAR* Name; FVector2D Min,Max; bool Soft; };','    inline const FRoom Rooms[]={']
for name,(x0,y0,x1,y1),floor,_ in m.ROOMS:lines.append(f'        {{TEXT("{name}"),{{{x0},{y0}}},{{{x1},{y1}}},{str(floor=="carpet").lower()}}},')
lines+=['    };','    inline int32 RoomAt(FVector P) { for (int32 I=0;I<RoomCount;++I) if (P.X>=Rooms[I].Min.X&&P.X<=Rooms[I].Max.X&&P.Y>=Rooms[I].Min.Y&&P.Y<=Rooms[I].Max.Y) return I;return -1; }','    inline const FVector Nodes[]={']
lines += [f'        {{{x},{y},90}},' for x,y in m.NODES]
lines += ['    };','    inline const FIntPoint Links[]={']+[f'        {{{a},{b}}},' for a,b in m.LINKS]+['    };',
 '    inline const int32 RoomNodes[]={'+','.join(map(str,m.ROOM_NODES))+'};',
 '    inline const int32 DoorNodes[]={'+','.join(map(str,sorted(set(m.DOOR_NODES))))+'};',
 '    inline const FVector OpenPortals[]={']
for axis,c,_,_,o,_,kind in m.PARTITIONS:
    if kind=='arch':lines.append(f'        {{{c if axis=="x" else o},{o if axis=="x" else c},154}},')
lines+=['    };','    inline const FVector PortalNormals[]={']
for axis,_,_,_,_,_,kind in m.PARTITIONS:
    if kind=='arch':lines.append('        {1,0,0},' if axis=='x' else '        {0,1,0},')
lines+=['    };']
for label,starts in [('Starts',m.STARTS),('LegacyStarts',m.LEGACY_STARTS)]:
    lines+=['    inline const FVector '+label+'[][2]={']+[f'        {{{{{a[0]},{a[1]},90}},{{{b[0]},{b[1]},90}}}},' for a,b in starts]+['    };']
lines+=['}']
destination=root/'Source/Spycho/SpychoHouseLayout.h'
content='\n'.join(lines)+'\n'
if not destination.exists() or destination.read_text(encoding='utf-8')!=content:
    destination.write_text(content,encoding='utf-8')
print('Generated',len(m.ROOMS),'rooms,',len(m.NODES),'nodes,',len(m.LINKS),'links')
